export const IMAGES = {
  splash: require('../../assets/images/pair-trainers.jpg'),
  shoes1: require('../../assets/images/shoes1.png'),
  shoes2: require('../../assets/images/shoes2.png'),
  shoes3: require('../../assets/images/shoes3.png'),
  dots3: require('../../assets/images/dots.png'),
  shoes5: require('../../assets/images/shoes5.png'),
  shoes6: require('../../assets/images/shoes6.png'),
  shoes7: require('../../assets/images/shoes7.png'),
  under: require('../../assets/images/under.png'),
  addias: require('../../assets/images/addias.png'),
  converse: require('../../assets/images/converse.png'),
  puma: require('../../assets/images/puma.png'),
  nike: require('../../assets/images/nike.png'),
  line: require('../../assets/images/lines.png'),
  map: require('../../assets/images/Map.png'),
  profile: require('../../assets/images/profile.png'),
  default: require('../../assets/images/default.png'),
};
